In [55]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2' # warning + error

In [56]:
sess = tf.InteractiveSession()
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################
x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
print(x.eval())
print(y.eval())
out = tf.cond(tf.greater(x, y), lambda: x + y, lambda: x - y)
print(sess.run(out))

0.074180484
0.47967994
1.0893682


In [58]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################
x = tf.random_uniform([],-1,1)  # (shape,min,max) range in [min,max)
y = tf.random_uniform([],-1,1) 
print(x.eval())
print(y.eval())
out = tf.case({
                tf.less(x,y): lambda: tf.add(x,y) ,
                tf.greater(x,y): lambda: tf.subtract(x,y),
              },
            default= lambda: tf.constant(0.),
            exclusive=True)
print(sess.run(out))

-0.3602655
0.6577325
-0.15120411


我估計他在跑sess.run(out)的時候才會有新的x,y 不然值都不符合

In [61]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################
x = tf.constant([[0,-2,1],[0,1,2]])
y = tf.zeros_like(x)
print(sess.run(tf.equal(x,y)))

[[ True False False]
 [ True False False]]


In [68]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################
x = tf.constant(
    [29.05088806,  27.61298943,  31.19073486,  29.35532951,
    30.97266006,  26.67541885,  38.08450317,  20.74983215,
    34.94445419,  34.45999146,  29.06485367,  36.01657104,
    27.88236427,  20.56035233,  30.20379066,  29.51215172,
    33.71149445,  28.59134293,  36.05556488,  28.66994858])
idx = tf.where(tf.greater(x,30.))
print(idx.eval())
out = tf.gather(x,idx)
print(out.eval())

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
[[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


In [72]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################
x=tf.range(1,7)
print(tf.diag(x).eval())

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


matrix_diag 也是一種方法

In [76]:
x=tf.range(1,9)
x=tf.reshape(x,[2,4])
print(x.eval())
print(tf.matrix_diag(x).eval())

[[1 2 3 4]
 [5 6 7 8]]
[[[1 0 0 0]
  [0 2 0 0]
  [0 0 3 0]
  [0 0 0 4]]

 [[5 0 0 0]
  [0 6 0 0]
  [0 0 7 0]
  [0 0 0 8]]]


為了驗證正確性 我用2x2 

In [87]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################
x = tf.random_normal([2,2])
print(x.eval())
print(tf.matrix_determinant(x).eval())
y = tf.constant([[2.,3.],[1.,2.]])
print(y.eval())
print(tf.matrix_determinant(y).eval())

[[-0.7758407  -0.25497925]
 [ 0.7823821  -0.5999962 ]]
-0.591647
[[2. 3.]
 [1. 2.]]
1.0


試了好幾遍 output都是錯誤的 看來實際跑的x和上面的x不同啊   正+正不可能<0阿

In [93]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
y , idx = tf.unique(x)
print(y.eval())
print(idx.eval())

[ 5  2  3 10  6  4  1  0  9]
[0 1 2 0 3 4 1 2 5 1 6 6 7 8]


In [100]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################
x = tf.random_normal([300])
y = tf.random_normal([300])
def f1(): return tf.reduce_mean(tf.square(x-y))
def f2(): return tf.reduce_sum(tf.abs(x-y))
print(tf.cond(tf.reduce_mean(x-y) < 0,f1,f2).eval())

1.9814825


In [101]:
def huber_loss(labels, predictions, delta=14.0):
    residual = tf.abs(labels - predictions)
    def f1(): return 0.5 * tf.square(residual)
    def f2(): return delta * residual - 0.5 * tf.square(delta)
    return tf.cond(residual < delta, f1, f2)
